baseURL = "https://clpatterson.github.io/"
languageCode = "en-us"
title = "Charlie Patterson"
theme = "ezhil-fork"
publishDir = "public"

copyright = "© Copyright 2025 Charlie Patterson"

# Enable syntax highlighting.
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Your Google analytics code.
# googleAnalytics = ""
# Your Disqus sortname.
disqusShortname = ""

# Number of posts to show in recent posts list (Optional). Defaults to 10.
pagination.pagerSize = 10

# Number of characters to show in summary.
summaryLength = 20

[params]
    # Blog subtitle which appears below blog title. Supports markdown.
    subtitle = "Bits of code, reflections, and projects for the sake of learning"

    # Content types which are included in home page recent posts list.
    mainSections = ["posts"]

    # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
    featherIconsCDN = true

    # Switch to dark mode or auto detect mode from OS (Optional).
    # "dark" will set mode to dark and "auto" will switch to dark mode if OS is in dark mode.
    mode = "auto" # "dark" or "auto"

# Main menu which appears below site header.
[[menu.main]]
name = "Blog"
url = "/"
weight = 1

[[menu.main]]
name = "Learning Journal"
url = "/learning-journal"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/clpatterson"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/pattersoncharlesl/"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

